---
- hosts: source
  sudo: yes
  roles:
    - role: pcap-replay

- hosts: router
  sudo: yes
  roles:
    - role: dpdk

- hosts: sink
  sudo: yes
  tasks:
  - name: Install dependencies
    yum: name=* state=present
    with_items:
      - "@Development tools"
      - pciutils
      - net-tools
      - bind-utils
      - tcpdump
