---
  - name: "Download DPDK version {{ dpdk_version }}"
    unarchive:
      src: "http://dpdk.org/browse/dpdk/snapshot/dpdk-{{ dpdk_version }}.tar.gz"
      dest: "/root"
      creates: "/root/dpdk-{{ dpdk_version }}"
      copy: no

  - name: "Build DPDK for the target environment: {{ dpdk_target }}"
    shell: "make install T={{ dpdk_target }} DESTDIR={{ dpdk_home }}"
    args:
      chdir: "/root/dpdk-{{ dpdk_version }}"
      creates: "{{ dpdk_home }}"

  - name: Load kernel modules to enable userspace IO
    shell: "{{ item }}"
    with_items:
      - modprobe uio_pci_generic
      - modprobe vfio-pci

  - name: Bind the device to the loaded kernel module(s)
    shell: "{{ dpdk_home }}/sbin/dpdk_nic_bind --force --bind=uio_pci_generic {{ item }}"
    with_items: "{{ dpdk_device }}"

  - name: Set useful environment variables
    lineinfile: "dest=/root/.bash_profile line={{ item }}"
    with_items:
      - "export RTE_SDK=/root/dpdk-{{ dpdk_version }}"
      - "export RTE_TARGET={{ dpdk_target }}"
